@startuml
class AttributClasse {
+cardinalitePointeur : String
+cardinalitePointee : String
+ getAttribut() : Classe
+ setCardinalitePointee(String) : void
+ getCardinalitePointee() : String
+ setCardinalitePointeur(String) : void
+ getCardinalitePointeur() : String
+ toString() : String
}
AttributClasse --> Classe : attribut
class Classe {
+PUBLIC : String
+PRIVATE : String
+PROTECTED : String
+CLASS : String
+INTERFACE : String
+ABSTRACT : String
+nom : String
+acces : String
+type : String
+parents : ArrayList
+attributs : ArrayList
+methodes : ArrayList
+ updateAttributs() : void
+ getAttributs() : ArrayList
+ getMethodes() : ArrayList
+ addAttribut(Attribut) : void
- adjustPath(String, int) : String
+ getParents() : ArrayList
+ addMethode(Methode) : void
+ addParent(Classe) : void
+ getNom() : String
+ getAcces() : String
+ toString() : String
+ getType() : String
}
@enduml
