@startuml
class Classe {
+PUBLIC : String
+PRIVATE : String
+PROTECTED : String
+CLASS : String
+INTERFACE : String
+ABSTRACT : String
+nom : String
+acces : String
+type : String
+parents : ArrayList
+attributs : ArrayList
+methodes : ArrayList
+ getAttributs() : ArrayList
+ getMethodes() : ArrayList
+ addAttribut(Attribut) : void
+ updateAttributs() : void
+ addMethode(Methode) : void
+ getParents() : ArrayList
+ addParent(Classe) : void
+ getNom() : String
+ getAcces() : String
- adjustPath(String, int) : String
+ toString() : String
+ getType() : String
}
class AttributClasse {
+cardinalitePointeur : String
+cardinalitePointee : String
+ getAttribut() : Classe
+ getCardinalitePointee() : String
+ setCardinalitePointee(String) : void
+ getCardinalitePointeur() : String
+ setCardinalitePointeur(String) : void
+ toString() : String
}
AttributClasse --> Classe : attribut
class Attribut {
+nom : String
+typeAcces : String
+type : String
+ setType(String) : void
+ setTypeAcces(String) : void
+ getTypeAcces() : String
+ getNom() : String
+ setNom(String) : void
+ toString() : String
+ getType() : String
}
class Methode {
+nom : String
+acces : String
+typeRetour : String
+parametres : ArrayList
+ getTypeRetour() : String
+ setTypeRetour(String) : void
+ getParametres() : ArrayList
+ setParametres(ArrayList) : void
+ getNom() : String
+ getAcces() : String
+ setNom(String) : void
+ setAcces(String) : void
+ toString() : String
}
class Diagramme {
+nomPackage : String
+listeClasses : ArrayList
+ supprimerClasse(Classe) : void
+ updateClasses() : void
+ ajouterClasse(Classe) : void
+ getNomPackage() : String
+ getListeClasses() : ArrayList
+ setListeClasses(ArrayList) : void
+ setNomPackage(String) : void
+ toString() : String
+ getInstance() : Diagramme
+ initialize(String, ArrayList) : void
}
Diagramme --> Diagramme : instance
class Exporter {
+ getDiagramme() : Diagramme
+ exportUML() : void
}
Exporter --> Diagramme : diagramme
@enduml
