@startuml
title Affichage du diagramme

actor "Vincent" as Utilisateur
participant "main : Main" as Main
participant "vueClasse : VueClasse" as VueClasse

activate Main
Utilisateur -> Main : clique sur le bouton "afficher"
loop nbClasses fois
    create VueClasse
    Main -> VueClasse : new VueClasse(classe)
    Main -> VueClasse : getLongueur()
    activate VueClasse
    VueClasse --> Main : double
    deactivate VueClasse

    Main -> VueClasse : getLargeur()
    activate VueClasse
    VueClasse --> Main : double
    deactivate VueClasse

    Main -> VueClasse : relocate(longueur, largeur)
    activate VueClasse
    VueClasse --> Main :
    deactivate VueClasse
end
Main --> Utilisateur : affichage

@enduml