@startuml
title Diagramme de classes de l'application - Itération 4

class Diagramme <<Singleton>> {
-nomPackage : String
+ {static} getInstance() : Diagramme
+ {static}initialize(String, ArrayList) : void
+ ajouterClasse(Classe) : void
+ getListeClasses() : ArrayList
+ getClasse(String) : Classe
+ supprimerClasse(Classe) : void
+ setNomPackage(String) : void
+ getNomPackage() : String
+ ajouterObservateur(Observateur) : void
+ notifierObservateurs() : void
+ supprimerObservateur(Observateur) : void
+ updateClasses() : void
+<color:royalBlue>afficherTousAttributs() : void
+<color:royalBlue>masquerTousAttributs() : void
+<color:royalBlue>afficherToutesMethodes() : void
+<color:royalBlue>masquerToutesMethodes() : void
+ toString() : String
}
Diagramme ..|> Sujet
Diagramme --> Classe : listeClasses
Diagramme --> Diagramme : instance
Diagramme --> Observateur : listeObservateurs

class Attribut {
-nom : String
-typeAcces : String
-type : String
-visible : boolean
+ setVisible(boolean) : void
+ isVisible() : boolean
+<color:royalBlue>toPlantUML() : String
+ toString() : String
}

class AttributClasse {
-cardinalitePointeur : String
-cardinalitePointee : String
+ toString() : String
+ setCardinalitePointee(String) : void
+ getCardinalitePointee() : String
+ getCardinalitePointeur() : String
+ setCardinalitePointeur(String) : void
+ getAttribut() : Classe
}
AttributClasse --|> Attribut
AttributClasse --> Classe : attribut

class Methode {
-nom : String
-acces : String
-typeRetour : String
-parametres : ArrayList<String>
-visible : boolean
+ setVisible(boolean) : void
+ isVisible() : boolean
+<color:royalBlue>toPlantUML() : String
+ toString() : String
}

class Exporter <<Record>> {
+ diagramme() : Diagramme
+ exportUML() : void
}
Exporter --> Diagramme : diagramme

class Classe {
-nom : String
-acces : String
-type : String
-visible : boolean
-longueur : double
-largeur : double
+ getLongueur() : double
+ setLongueur(double) : void
+ addParent(Classe) : void
- adjustPath(String, int) : String
+ addMethode(Methode) : void
+ setVisible(boolean) : void
+ getLargeur() : double
+ setLargeur(double) : void
+ updateAttributs() : void
+ getMethodes() : ArrayList
+ getAttributs() : ArrayList
+ addAttribut(Attribut) : void
+ isVisible() : boolean
+<color:royalBlue>getTypeClasseString() : String
+<color:royalBlue>afficherAttributs() : void
+<color:royalBlue>afficherMethodes() : void
+<color:royalBlue>afficherParents() : void
+<color:royalBlue>masquerAttributs() : void
+<color:royalBlue>masquerMethodes() : void
+<color:royalBlue>masquerParents() : void
+ toPlantUML() : String
+ toString() : String
}
Classe --> Classe : parents
Classe --> Attribut : attributs
Classe --> Methode : methodes

interface Sujet {
 ajouterObservateur(Observateur) : void
 notifierObservateurs() : void
 supprimerObservateur(Observateur) : void
}
interface Observateur {
 actualiser() : void
}
class VueClasse {
+  actualiser() : void
-<color:royalBlue>initialiserComportement() : void
+<color:royalBlue>estVisibleClasse() : boolean
-<color:royalBlue>createTypeIndicator() : StackPane
-<color:royalBlue>createAccessIndicator() : StackPane
}
VueClasse ..|> Observateur
VueClasse --|> VBox
VueClasse --> Classe : classe

class ControleurVisibilite {
+ handle(ActionEvent) : void
}
ControleurVisibilite --> Classe : classe


class VueListeClasses ##royalBlue {
+<color:royalBlue>actualiser() : void
+<color:royalBlue>updateListe() : void
}
VueListeClasses .[#royalBlue].|> Observateur
VueListeClasses -[#royalBlue]-|> VBox
VueListeClasses -[#royalBlue]-> Diagramme : diagramme

@enduml